name: flutter_emoji_picker
description: 'An simple emojis picker that makes too easy select emojis from any platform'
version: 1.0.1
homepage: https://github.com/CatHood0/emoji_picker/ 
issue_tracker: https://github.com/CatHood0/emoji_picker/issues/  
documentation: https://github.com/CatHood0/emoji_picker/ 

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - ui
  - picker
  - emojis
  - widgets
  - emojis-picker

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter

  eva_icons_flutter: ^3.1.0
  equatable: ^2.0.5 
  collection: ^1.18.0 
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
